name: API tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
  
jobs:
  build:
    name: API automated tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      - name: Run the API tests
        run: mvn clean test
